spring.application.name=secority

spring.security.user.name = aman
spring.security.user.password = pass


# DataSource
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=authanti;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=8619113110Aman#
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect